# Generated by Django 4.2.19 on 2025-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="About Us", max_length=255)),
                (
                    "subtitle",
                    models.CharField(
                        default="Our Journey, Your Delight", max_length=255
                    ),
                ),
                (
                    "paragraph1",
                    models.TextField(
                        default="Welcome to [Your Restaurant Name], where passion meets flavor! Our story began with a simple dream: to create a dining experience that celebrates the art of cooking and the joy of sharing meals. Inspired by [specific inspiration, e.g., family recipes, cultural heritage, or a love for fresh ingredients], we craft every dish with care and creativity."
                    ),
                ),
                (
                    "paragraph2",
                    models.TextField(
                        default="What makes our food special? It’s the perfect blend of tradition and innovation. We source the finest ingredients, often locally and sustainably, to ensure every bite is bursting with freshness and flavor. From our signature [specific dish] to our ever-evolving seasonal menu, we strive to bring you a culinary journey that delights the senses."
                    ),
                ),
                (
                    "paragraph3",
                    models.TextField(
                        default="But it’s not just about the food—it’s about the people. Our team is dedicated to making every visit memorable, whether you’re joining us for a casual lunch, a romantic dinner, or a special celebration. At [Your Restaurant Name], you’re not just a guest; you’re part of our story."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Business email address", max_length=254, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Business address (optional)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="Enter the FAQ question", max_length=255
                    ),
                ),
                (
                    "answer",
                    models.TextField(help_text="Enter the answer to the FAQ question"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload a gallery image", upload_to="gallery/"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        help_text="Short caption for the image", max_length=255
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Welcome to Our Restaurant", max_length=255
                    ),
                ),
                (
                    "paragraph",
                    models.TextField(
                        default="Experience the finest dining with our exquisite menu and cozy ambiance."
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="hero_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the restaurant or location", max_length=255
                    ),
                ),
                ("map_embed_link", models.URLField(help_text="Google Maps embed link")),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="menu_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter a valid email address",
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("date_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True, help_text="Facebook profile or page URL"
                    ),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, help_text="Instagram profile URL"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, help_text="Twitter (X) profile URL"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                (
                    "time_limit",
                    models.CharField(
                        help_text="E.g., 'Limited time offer until Sunday!'",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "★"),
                            (2, "★★"),
                            (3, "★★★"),
                            (4, "★★★★"),
                            (5, "★★★★★"),
                        ],
                        default=5,
                    ),
                ),
                ("review", models.TextField()),
            ],
        ),
    ]
